
run:
	yap -l test.pl 

# Try as input to the REPL: example1(L,R). Then step through with ";" a few times to get all the solutions. Exit with Ctrl-d.
# Alternative: 

run2: 
	gprolog --consult-file test.pl

#  [ rinst(i:r1,nil,[],rte_enter(x,Cont1)), excl(i:z,free), rinst(i:r2,nil,[],rte_enter(x,Cont2)), excl(i:x,free) ] ---L---> R.
